const devMode = process.env.NODE_ENV !== `production`;

// Глобальные (для всех компонентов) Vue-миксины
const mixins = [];
require(`fs`).readdirSync(`plugins/mixins/global`).forEach((file) => {
  mixins.push(`@/plugins/mixins/global/${file}`);
});

export default {
  // Доступно из *.vue как process.env
  env: {
    isDev: devMode
  },

  loading: {
    color: `#ffffff`
  },

  build: {
    extend(config, { isDev, isClient }) {
      if (isDev && isClient) {
        // Вызов eslint при сохранении файла
        config.module.rules.push({
          enforce: `pre`,
          test: /\.(js|vue)$/,
          loader: `eslint-loader`,
          exclude: /(node_modules|dist)/
        });
      }
    },

    filenames: {
      app: ({ isDev }) => isDev ? `[name].js` : `js/[name].js`,
      chunk: ({ isDev }) => isDev ? `[name].js` : `js/[name].js`,
      css: ({ isDev }) => isDev ? `[path][name].[ext]` : `css/styles.css`,
      img: ({ isDev }) => isDev ? `[path][name].[ext]` : `img/[name].[ext]`,
      font: ({ isDev }) => isDev ? `[path][name].[ext]` : `fonts/[name].[ext]`,
      video: ({ isDev }) => isDev ? `[path][name].[ext]` : `videos/[name].[ext]`
    },

    html: {
      minify: {
        collapseBooleanAttributes: true,
        collapseWhitespace: true,
        decodeEntities: true,
        html5: true,
        includeAutoGeneratedTags: false,
        minifyCSS: true,
        minifyJS: true,
        quoteCharacter: `"`,
        processConditionalComments: true,
        removeComments: true,
        removeEmptyAttributes: true,
        removeRedundantAttributes: true,
        removeScriptTypeAttributes: true,
        removeStyleLinkTypeAttributes: true,
        trimCustomFragments: true,
        useShortDoctype: true
      }
    },

    splitChunks: {
      layouts: false,
      pages: false,
      commons: false
    },

    extractCSS: !devMode,
    terser: true,
    publicPath: devMode ? `http://localhost:3000` : `/`
  },

  generate: {
    dir: `build`,
    subFolders: false
  },

  plugins: [
    `@/plugins/components.js`,
    ...mixins
  ],

  modules: [
    `@nuxtjs/style-resources`,
    `nuxt-svg`
  ],

  css: [
    `@/assets/scss/styles.scss`
  ],
  styleResources: {
    scss: [
      `assets/scss/variables.scss`
    ]
  }
};
